# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.dream_daemon_api import DreamDaemonApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDreamDaemonApi(unittest.TestCase):
    """DreamDaemonApi unit test stubs"""

    def setUp(self):
        self.api = DreamDaemonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dream_daemon_controller_create(self):
        """Test case for dream_daemon_controller_create

        Launches the watchdog.  # noqa: E501
        """
        pass

    def test_dream_daemon_controller_create_dump(self):
        """Test case for dream_daemon_controller_create_dump

        Creates a Tgstation.Server.Api.Models.Response.JobResponse to generate a DreamDaemon process dump.  # noqa: E501
        """
        pass

    def test_dream_daemon_controller_delete(self):
        """Test case for dream_daemon_controller_delete

        Stops the Watchdog if it's running.  # noqa: E501
        """
        pass

    def test_dream_daemon_controller_read(self):
        """Test case for dream_daemon_controller_read

        Get the watchdog status.  # noqa: E501
        """
        pass

    def test_dream_daemon_controller_restart(self):
        """Test case for dream_daemon_controller_restart

        Creates a Tgstation.Server.Api.Models.Response.JobResponse to restart the Watchdog. It will not start if it wasn't already running.  # noqa: E501
        """
        pass

    def test_dream_daemon_controller_update(self):
        """Test case for dream_daemon_controller_update

        Update watchdog settings to be applied at next server reboot.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
