# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_instance_permission_set_request_configuration_rights import AllOfInstancePermissionSetRequestConfigurationRights  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfInstancePermissionSetRequestConfigurationRights(unittest.TestCase):
    """AllOfInstancePermissionSetRequestConfigurationRights unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfInstancePermissionSetRequestConfigurationRights(self):
        """Test AllOfInstancePermissionSetRequestConfigurationRights"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_instance_permission_set_request_configuration_rights.AllOfInstancePermissionSetRequestConfigurationRights()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
