# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 8.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.body57 import Body57  # noqa: E501
from swagger_client.rest import ApiException


class TestBody57(unittest.TestCase):
    """Body57 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody57(self):
        """Test Body57"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body57.Body57()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
