# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 8.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_group_api import UserGroupApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserGroupApi(unittest.TestCase):
    """UserGroupApi unit test stubs"""

    def setUp(self):
        self.api = UserGroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_group_controller_create(self):
        """Test case for user_group_controller_create

        Create a new Tgstation.Server.Api.Models.UserGroup.  # noqa: E501
        """
        pass

    def test_user_group_controller_delete(self):
        """Test case for user_group_controller_delete

        Delete an Tgstation.Server.Api.Models.UserGroup.  # noqa: E501
        """
        pass

    def test_user_group_controller_get_id(self):
        """Test case for user_group_controller_get_id

        Gets a specific Tgstation.Server.Api.Models.UserGroup.  # noqa: E501
        """
        pass

    def test_user_group_controller_list(self):
        """Test case for user_group_controller_list

        Lists all Tgstation.Server.Api.Models.UserGroups.  # noqa: E501
        """
        pass

    def test_user_group_controller_update(self):
        """Test case for user_group_controller_update

        Update a Tgstation.Server.Api.Models.UserGroup.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
