# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 8.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.body67 import Body67  # noqa: E501
from swagger_client.rest import ApiException


class TestBody67(unittest.TestCase):
    """Body67 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody67(self):
        """Test Body67"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body67.Body67()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
