# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 8.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.paginated_log_file import PaginatedLogFile  # noqa: E501
from swagger_client.rest import ApiException


class TestPaginatedLogFile(unittest.TestCase):
    """PaginatedLogFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedLogFile(self):
        """Test PaginatedLogFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.paginated_log_file.PaginatedLogFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
