# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transfer_api import TransferApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransferApi(unittest.TestCase):
    """TransferApi unit test stubs"""

    def setUp(self):
        self.api = TransferApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_transfer_controller_download(self):
        """Test case for transfer_controller_download

        Downloads a file with a given ticket.  # noqa: E501
        """
        pass

    def test_transfer_controller_upload(self):
        """Test case for transfer_controller_upload

        Uploads a file with a given ticket.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
