# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.administration_api import AdministrationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAdministrationApi(unittest.TestCase):
    """AdministrationApi unit test stubs"""

    def setUp(self):
        self.api = AdministrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_administration_controller_delete(self):
        """Test case for administration_controller_delete

        Attempts to restart the server.  # noqa: E501
        """
        pass

    def test_administration_controller_get_log(self):
        """Test case for administration_controller_get_log

        Download a Tgstation.Server.Api.Models.Response.LogFileResponse.  # noqa: E501
        """
        pass

    def test_administration_controller_list_logs(self):
        """Test case for administration_controller_list_logs

        List Tgstation.Server.Api.Models.Response.LogFileResponses present.  # noqa: E501
        """
        pass

    def test_administration_controller_read(self):
        """Test case for administration_controller_read

        Get Tgstation.Server.Api.Models.Response.AdministrationResponse server information.  # noqa: E501
        """
        pass

    def test_administration_controller_update(self):
        """Test case for administration_controller_update

        Attempt to perform a server upgrade.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
