# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 8.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_error_message_error_code import AllOfErrorMessageErrorCode  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfErrorMessageErrorCode(unittest.TestCase):
    """AllOfErrorMessageErrorCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfErrorMessageErrorCode(self):
        """Test AllOfErrorMessageErrorCode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_error_message_error_code.AllOfErrorMessageErrorCode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
