# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 8.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.instance_permission_set_rights import InstancePermissionSetRights  # noqa: E501
from swagger_client.rest import ApiException


class TestInstancePermissionSetRights(unittest.TestCase):
    """InstancePermissionSetRights unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstancePermissionSetRights(self):
        """Test InstancePermissionSetRights"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.instance_permission_set_rights.InstancePermissionSetRights()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
