# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.repository_api import RepositoryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRepositoryApi(unittest.TestCase):
    """RepositoryApi unit test stubs"""

    def setUp(self):
        self.api = RepositoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_repository_controller_create(self):
        """Test case for repository_controller_create

        Begin cloning the repository if it doesn't exist.  # noqa: E501
        """
        pass

    def test_repository_controller_delete(self):
        """Test case for repository_controller_delete

        Delete the repository.  # noqa: E501
        """
        pass

    def test_repository_controller_read(self):
        """Test case for repository_controller_read

        Get the repository's status.  # noqa: E501
        """
        pass

    def test_repository_controller_update(self):
        """Test case for repository_controller_update

        Perform updates to the repository.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
