# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_user_group_permission_set import AllOfUserGroupPermissionSet  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfUserGroupPermissionSet(unittest.TestCase):
    """AllOfUserGroupPermissionSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfUserGroupPermissionSet(self):
        """Test AllOfUserGroupPermissionSet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_user_group_permission_set.AllOfUserGroupPermissionSet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
