# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 8.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.shallow_user_group import ShallowUserGroup  # noqa: E501
from swagger_client.rest import ApiException


class TestShallowUserGroup(unittest.TestCase):
    """ShallowUserGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShallowUserGroup(self):
        """Test ShallowUserGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.shallow_user_group.ShallowUserGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
