# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.dream_maker_api import DreamMakerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDreamMakerApi(unittest.TestCase):
    """DreamMakerApi unit test stubs"""

    def setUp(self):
        self.api = DreamMakerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dream_maker_controller_create(self):
        """Test case for dream_maker_controller_create

        Begin deploying repository code.  # noqa: E501
        """
        pass

    def test_dream_maker_controller_get_id(self):
        """Test case for dream_maker_controller_get_id

        Get a Tgstation.Server.Host.Models.CompileJob specified by a given id.  # noqa: E501
        """
        pass

    def test_dream_maker_controller_list(self):
        """Test case for dream_maker_controller_list

        List all Tgstation.Server.Host.Models.CompileJobTgstation.Server.Api.Models.EntityIds for the instance.  # noqa: E501
        """
        pass

    def test_dream_maker_controller_read(self):
        """Test case for dream_maker_controller_read

        Read current deployment settings.  # noqa: E501
        """
        pass

    def test_dream_maker_controller_update(self):
        """Test case for dream_maker_controller_update

        Update deployment settings.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
