# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.instance_permission_set_api import InstancePermissionSetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInstancePermissionSetApi(unittest.TestCase):
    """InstancePermissionSetApi unit test stubs"""

    def setUp(self):
        self.api = InstancePermissionSetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_instance_permission_set_controller_create(self):
        """Test case for instance_permission_set_controller_create

        Create an Tgstation.Server.Host.Models.InstancePermissionSet.  # noqa: E501
        """
        pass

    def test_instance_permission_set_controller_delete(self):
        """Test case for instance_permission_set_controller_delete

        Delete an Tgstation.Server.Host.Models.InstancePermissionSet.  # noqa: E501
        """
        pass

    def test_instance_permission_set_controller_get_id(self):
        """Test case for instance_permission_set_controller_get_id

        Gets a specific Tgstation.Server.Api.Models.Internal.InstancePermissionSet.  # noqa: E501
        """
        pass

    def test_instance_permission_set_controller_list(self):
        """Test case for instance_permission_set_controller_list

        Lists Tgstation.Server.Host.Models.InstancePermissionSets for the instance.  # noqa: E501
        """
        pass

    def test_instance_permission_set_controller_read(self):
        """Test case for instance_permission_set_controller_read

        Read the active Tgstation.Server.Host.Models.InstancePermissionSet.  # noqa: E501
        """
        pass

    def test_instance_permission_set_controller_update(self):
        """Test case for instance_permission_set_controller_update

        Update the permissions for an Tgstation.Server.Host.Models.InstancePermissionSet.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
