# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.configuration_file_response import ConfigurationFileResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigurationFileResponse(unittest.TestCase):
    """ConfigurationFileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigurationFileResponse(self):
        """Test ConfigurationFileResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.configuration_file_response.ConfigurationFileResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
