# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ByondVersionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'upload_custom_zip': 'bool'
    }

    attribute_map = {
        'version': 'version',
        'upload_custom_zip': 'uploadCustomZip'
    }

    def __init__(self, version=None, upload_custom_zip=None):  # noqa: E501
        """ByondVersionRequest - a model defined in Swagger"""  # noqa: E501
        self._version = None
        self._upload_custom_zip = None
        self.discriminator = None
        if version is not None:
            self.version = version
        if upload_custom_zip is not None:
            self.upload_custom_zip = upload_custom_zip

    @property
    def version(self):
        """Gets the version of this ByondVersionRequest.  # noqa: E501

        The BYOND version to install.  # noqa: E501

        :return: The version of this ByondVersionRequest.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ByondVersionRequest.

        The BYOND version to install.  # noqa: E501

        :param version: The version of this ByondVersionRequest.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def upload_custom_zip(self):
        """Gets the upload_custom_zip of this ByondVersionRequest.  # noqa: E501

        If a custom BYOND version is to be uploaded.  # noqa: E501

        :return: The upload_custom_zip of this ByondVersionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._upload_custom_zip

    @upload_custom_zip.setter
    def upload_custom_zip(self, upload_custom_zip):
        """Sets the upload_custom_zip of this ByondVersionRequest.

        If a custom BYOND version is to be uploaded.  # noqa: E501

        :param upload_custom_zip: The upload_custom_zip of this ByondVersionRequest.  # noqa: E501
        :type: bool
        """

        self._upload_custom_zip = upload_custom_zip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ByondVersionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ByondVersionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
