# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 8.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Byond(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'install_job': 'AllOfByondInstallJob',
        'upload_custom_zip': 'bool',
        'file_ticket': 'str'
    }

    attribute_map = {
        'version': 'version',
        'install_job': 'installJob',
        'upload_custom_zip': 'uploadCustomZip',
        'file_ticket': 'fileTicket'
    }

    def __init__(self, version=None, install_job=None, upload_custom_zip=None, file_ticket=None):  # noqa: E501
        """Byond - a model defined in Swagger"""  # noqa: E501
        self._version = None
        self._install_job = None
        self._upload_custom_zip = None
        self._file_ticket = None
        self.discriminator = None
        if version is not None:
            self.version = version
        if install_job is not None:
            self.install_job = install_job
        if upload_custom_zip is not None:
            self.upload_custom_zip = upload_custom_zip
        if file_ticket is not None:
            self.file_ticket = file_ticket

    @property
    def version(self):
        """Gets the version of this Byond.  # noqa: E501

        The System.Version of the Tgstation.Server.Api.Models.Byond installation used for new compiles. Will be <see langword=\"null\" /> if the user does not have permission to view it or there is no BYOND version installed. Only considers the System.Version.Major and System.Version.Minor numbers.  # noqa: E501

        :return: The version of this Byond.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this Byond.

        The System.Version of the Tgstation.Server.Api.Models.Byond installation used for new compiles. Will be <see langword=\"null\" /> if the user does not have permission to view it or there is no BYOND version installed. Only considers the System.Version.Major and System.Version.Minor numbers.  # noqa: E501

        :param version: The version of this Byond.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def install_job(self):
        """Gets the install_job of this Byond.  # noqa: E501

        The Tgstation.Server.Api.Models.Job being used to install a new Tgstation.Server.Api.Models.Byond.Version  # noqa: E501

        :return: The install_job of this Byond.  # noqa: E501
        :rtype: AllOfByondInstallJob
        """
        return self._install_job

    @install_job.setter
    def install_job(self, install_job):
        """Sets the install_job of this Byond.

        The Tgstation.Server.Api.Models.Job being used to install a new Tgstation.Server.Api.Models.Byond.Version  # noqa: E501

        :param install_job: The install_job of this Byond.  # noqa: E501
        :type: AllOfByondInstallJob
        """

        self._install_job = install_job

    @property
    def upload_custom_zip(self):
        """Gets the upload_custom_zip of this Byond.  # noqa: E501

        If a custom BYOND version is to be uploaded.  # noqa: E501

        :return: The upload_custom_zip of this Byond.  # noqa: E501
        :rtype: bool
        """
        return self._upload_custom_zip

    @upload_custom_zip.setter
    def upload_custom_zip(self, upload_custom_zip):
        """Sets the upload_custom_zip of this Byond.

        If a custom BYOND version is to be uploaded.  # noqa: E501

        :param upload_custom_zip: The upload_custom_zip of this Byond.  # noqa: E501
        :type: bool
        """

        self._upload_custom_zip = upload_custom_zip

    @property
    def file_ticket(self):
        """Gets the file_ticket of this Byond.  # noqa: E501

        The ticket to use to access the Tgstation.Server.Api.Routes.Transfer controller.  # noqa: E501

        :return: The file_ticket of this Byond.  # noqa: E501
        :rtype: str
        """
        return self._file_ticket

    @file_ticket.setter
    def file_ticket(self, file_ticket):
        """Sets the file_ticket of this Byond.

        The ticket to use to access the Tgstation.Server.Api.Routes.Transfer controller.  # noqa: E501

        :param file_ticket: The file_ticket of this Byond.  # noqa: E501
        :type: str
        """

        self._file_ticket = file_ticket

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Byond, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Byond):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
