# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OAuthConnection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'provider': 'AllOfOAuthConnectionProvider',
        'external_user_id': 'str'
    }

    attribute_map = {
        'provider': 'provider',
        'external_user_id': 'externalUserId'
    }

    def __init__(self, provider=None, external_user_id=None):  # noqa: E501
        """OAuthConnection - a model defined in Swagger"""  # noqa: E501
        self._provider = None
        self._external_user_id = None
        self.discriminator = None
        if provider is not None:
            self.provider = provider
        if external_user_id is not None:
            self.external_user_id = external_user_id

    @property
    def provider(self):
        """Gets the provider of this OAuthConnection.  # noqa: E501

        The Tgstation.Server.Api.Models.OAuthProvider of the Tgstation.Server.Api.Models.OAuthConnection.  # noqa: E501

        :return: The provider of this OAuthConnection.  # noqa: E501
        :rtype: AllOfOAuthConnectionProvider
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this OAuthConnection.

        The Tgstation.Server.Api.Models.OAuthProvider of the Tgstation.Server.Api.Models.OAuthConnection.  # noqa: E501

        :param provider: The provider of this OAuthConnection.  # noqa: E501
        :type: AllOfOAuthConnectionProvider
        """

        self._provider = provider

    @property
    def external_user_id(self):
        """Gets the external_user_id of this OAuthConnection.  # noqa: E501

        The ID of the user in the Tgstation.Server.Api.Models.OAuthConnection.Provider.  # noqa: E501

        :return: The external_user_id of this OAuthConnection.  # noqa: E501
        :rtype: str
        """
        return self._external_user_id

    @external_user_id.setter
    def external_user_id(self, external_user_id):
        """Sets the external_user_id of this OAuthConnection.

        The ID of the user in the Tgstation.Server.Api.Models.OAuthConnection.Provider.  # noqa: E501

        :param external_user_id: The external_user_id of this OAuthConnection.  # noqa: E501
        :type: str
        """

        self._external_user_id = external_user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OAuthConnection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OAuthConnection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
