# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OAuthProviderInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_id': 'str',
        'redirect_uri': 'str',
        'server_url': 'str'
    }

    attribute_map = {
        'client_id': 'clientId',
        'redirect_uri': 'redirectUri',
        'server_url': 'serverUrl'
    }

    def __init__(self, client_id=None, redirect_uri=None, server_url=None):  # noqa: E501
        """OAuthProviderInfo - a model defined in Swagger"""  # noqa: E501
        self._client_id = None
        self._redirect_uri = None
        self._server_url = None
        self.discriminator = None
        if client_id is not None:
            self.client_id = client_id
        if redirect_uri is not None:
            self.redirect_uri = redirect_uri
        if server_url is not None:
            self.server_url = server_url

    @property
    def client_id(self):
        """Gets the client_id of this OAuthProviderInfo.  # noqa: E501

        The client ID.  # noqa: E501

        :return: The client_id of this OAuthProviderInfo.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this OAuthProviderInfo.

        The client ID.  # noqa: E501

        :param client_id: The client_id of this OAuthProviderInfo.  # noqa: E501
        :type: str
        """

        self._client_id = client_id

    @property
    def redirect_uri(self):
        """Gets the redirect_uri of this OAuthProviderInfo.  # noqa: E501

        The redirect URL.  # noqa: E501

        :return: The redirect_uri of this OAuthProviderInfo.  # noqa: E501
        :rtype: str
        """
        return self._redirect_uri

    @redirect_uri.setter
    def redirect_uri(self, redirect_uri):
        """Sets the redirect_uri of this OAuthProviderInfo.

        The redirect URL.  # noqa: E501

        :param redirect_uri: The redirect_uri of this OAuthProviderInfo.  # noqa: E501
        :type: str
        """

        self._redirect_uri = redirect_uri

    @property
    def server_url(self):
        """Gets the server_url of this OAuthProviderInfo.  # noqa: E501

        The server URL.  # noqa: E501

        :return: The server_url of this OAuthProviderInfo.  # noqa: E501
        :rtype: str
        """
        return self._server_url

    @server_url.setter
    def server_url(self, server_url):
        """Sets the server_url of this OAuthProviderInfo.

        The server URL.  # noqa: E501

        :param server_url: The server_url of this OAuthProviderInfo.  # noqa: E501
        :type: str
        """

        self._server_url = server_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OAuthProviderInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OAuthProviderInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
