# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PermissionSet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'administration_rights': 'AllOfPermissionSetAdministrationRights',
        'instance_manager_rights': 'AllOfPermissionSetInstanceManagerRights'
    }

    attribute_map = {
        'id': 'id',
        'administration_rights': 'administrationRights',
        'instance_manager_rights': 'instanceManagerRights'
    }

    def __init__(self, id=None, administration_rights=None, instance_manager_rights=None):  # noqa: E501
        """PermissionSet - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._administration_rights = None
        self._instance_manager_rights = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if administration_rights is not None:
            self.administration_rights = administration_rights
        if instance_manager_rights is not None:
            self.instance_manager_rights = instance_manager_rights

    @property
    def id(self):
        """Gets the id of this PermissionSet.  # noqa: E501


        :return: The id of this PermissionSet.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PermissionSet.


        :param id: The id of this PermissionSet.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def administration_rights(self):
        """Gets the administration_rights of this PermissionSet.  # noqa: E501

        The Tgstation.Server.Api.Rights.AdministrationRights for the user.  # noqa: E501

        :return: The administration_rights of this PermissionSet.  # noqa: E501
        :rtype: AllOfPermissionSetAdministrationRights
        """
        return self._administration_rights

    @administration_rights.setter
    def administration_rights(self, administration_rights):
        """Sets the administration_rights of this PermissionSet.

        The Tgstation.Server.Api.Rights.AdministrationRights for the user.  # noqa: E501

        :param administration_rights: The administration_rights of this PermissionSet.  # noqa: E501
        :type: AllOfPermissionSetAdministrationRights
        """

        self._administration_rights = administration_rights

    @property
    def instance_manager_rights(self):
        """Gets the instance_manager_rights of this PermissionSet.  # noqa: E501

        The Tgstation.Server.Api.Rights.InstanceManagerRights for the user.  # noqa: E501

        :return: The instance_manager_rights of this PermissionSet.  # noqa: E501
        :rtype: AllOfPermissionSetInstanceManagerRights
        """
        return self._instance_manager_rights

    @instance_manager_rights.setter
    def instance_manager_rights(self, instance_manager_rights):
        """Sets the instance_manager_rights of this PermissionSet.

        The Tgstation.Server.Api.Rights.InstanceManagerRights for the user.  # noqa: E501

        :param instance_manager_rights: The instance_manager_rights of this PermissionSet.  # noqa: E501
        :type: AllOfPermissionSetInstanceManagerRights
        """

        self._instance_manager_rights = instance_manager_rights

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PermissionSet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PermissionSet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
