# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RepositoryResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'origin': 'str',
        'revision_information': 'AllOfRepositoryResponseRevisionInformation',
        'remote_git_provider': 'AllOfRepositoryResponseRemoteGitProvider',
        'remote_repository_owner': 'str',
        'remote_repository_name': 'str',
        'active_job': 'AllOfRepositoryResponseActiveJob',
        'reference': 'str',
        'committer_name': 'str',
        'committer_email': 'str',
        'access_user': 'str',
        'push_test_merge_commits': 'bool',
        'create_git_hub_deployments': 'bool',
        'show_test_merge_committers': 'bool',
        'auto_updates_keep_test_merges': 'bool',
        'auto_updates_synchronize': 'bool',
        'post_test_merge_comment': 'bool'
    }

    attribute_map = {
        'origin': 'origin',
        'revision_information': 'revisionInformation',
        'remote_git_provider': 'remoteGitProvider',
        'remote_repository_owner': 'remoteRepositoryOwner',
        'remote_repository_name': 'remoteRepositoryName',
        'active_job': 'activeJob',
        'reference': 'reference',
        'committer_name': 'committerName',
        'committer_email': 'committerEmail',
        'access_user': 'accessUser',
        'push_test_merge_commits': 'pushTestMergeCommits',
        'create_git_hub_deployments': 'createGitHubDeployments',
        'show_test_merge_committers': 'showTestMergeCommitters',
        'auto_updates_keep_test_merges': 'autoUpdatesKeepTestMerges',
        'auto_updates_synchronize': 'autoUpdatesSynchronize',
        'post_test_merge_comment': 'postTestMergeComment'
    }

    def __init__(self, origin=None, revision_information=None, remote_git_provider=None, remote_repository_owner=None, remote_repository_name=None, active_job=None, reference=None, committer_name=None, committer_email=None, access_user=None, push_test_merge_commits=None, create_git_hub_deployments=None, show_test_merge_committers=None, auto_updates_keep_test_merges=None, auto_updates_synchronize=None, post_test_merge_comment=None):  # noqa: E501
        """RepositoryResponse - a model defined in Swagger"""  # noqa: E501
        self._origin = None
        self._revision_information = None
        self._remote_git_provider = None
        self._remote_repository_owner = None
        self._remote_repository_name = None
        self._active_job = None
        self._reference = None
        self._committer_name = None
        self._committer_email = None
        self._access_user = None
        self._push_test_merge_commits = None
        self._create_git_hub_deployments = None
        self._show_test_merge_committers = None
        self._auto_updates_keep_test_merges = None
        self._auto_updates_synchronize = None
        self._post_test_merge_comment = None
        self.discriminator = None
        if origin is not None:
            self.origin = origin
        if revision_information is not None:
            self.revision_information = revision_information
        if remote_git_provider is not None:
            self.remote_git_provider = remote_git_provider
        if remote_repository_owner is not None:
            self.remote_repository_owner = remote_repository_owner
        if remote_repository_name is not None:
            self.remote_repository_name = remote_repository_name
        if active_job is not None:
            self.active_job = active_job
        if reference is not None:
            self.reference = reference
        if committer_name is not None:
            self.committer_name = committer_name
        if committer_email is not None:
            self.committer_email = committer_email
        if access_user is not None:
            self.access_user = access_user
        if push_test_merge_commits is not None:
            self.push_test_merge_commits = push_test_merge_commits
        if create_git_hub_deployments is not None:
            self.create_git_hub_deployments = create_git_hub_deployments
        if show_test_merge_committers is not None:
            self.show_test_merge_committers = show_test_merge_committers
        if auto_updates_keep_test_merges is not None:
            self.auto_updates_keep_test_merges = auto_updates_keep_test_merges
        if auto_updates_synchronize is not None:
            self.auto_updates_synchronize = auto_updates_synchronize
        if post_test_merge_comment is not None:
            self.post_test_merge_comment = post_test_merge_comment

    @property
    def origin(self):
        """Gets the origin of this RepositoryResponse.  # noqa: E501

        The origin URL. If <see langword=\"null\" />, the git repository does not currently exist on the server.  # noqa: E501

        :return: The origin of this RepositoryResponse.  # noqa: E501
        :rtype: str
        """
        return self._origin

    @origin.setter
    def origin(self, origin):
        """Sets the origin of this RepositoryResponse.

        The origin URL. If <see langword=\"null\" />, the git repository does not currently exist on the server.  # noqa: E501

        :param origin: The origin of this RepositoryResponse.  # noqa: E501
        :type: str
        """

        self._origin = origin

    @property
    def revision_information(self):
        """Gets the revision_information of this RepositoryResponse.  # noqa: E501

        The current Tgstation.Server.Api.Models.RevisionInformation.  # noqa: E501

        :return: The revision_information of this RepositoryResponse.  # noqa: E501
        :rtype: AllOfRepositoryResponseRevisionInformation
        """
        return self._revision_information

    @revision_information.setter
    def revision_information(self, revision_information):
        """Sets the revision_information of this RepositoryResponse.

        The current Tgstation.Server.Api.Models.RevisionInformation.  # noqa: E501

        :param revision_information: The revision_information of this RepositoryResponse.  # noqa: E501
        :type: AllOfRepositoryResponseRevisionInformation
        """

        self._revision_information = revision_information

    @property
    def remote_git_provider(self):
        """Gets the remote_git_provider of this RepositoryResponse.  # noqa: E501


        :return: The remote_git_provider of this RepositoryResponse.  # noqa: E501
        :rtype: AllOfRepositoryResponseRemoteGitProvider
        """
        return self._remote_git_provider

    @remote_git_provider.setter
    def remote_git_provider(self, remote_git_provider):
        """Sets the remote_git_provider of this RepositoryResponse.


        :param remote_git_provider: The remote_git_provider of this RepositoryResponse.  # noqa: E501
        :type: AllOfRepositoryResponseRemoteGitProvider
        """

        self._remote_git_provider = remote_git_provider

    @property
    def remote_repository_owner(self):
        """Gets the remote_repository_owner of this RepositoryResponse.  # noqa: E501


        :return: The remote_repository_owner of this RepositoryResponse.  # noqa: E501
        :rtype: str
        """
        return self._remote_repository_owner

    @remote_repository_owner.setter
    def remote_repository_owner(self, remote_repository_owner):
        """Sets the remote_repository_owner of this RepositoryResponse.


        :param remote_repository_owner: The remote_repository_owner of this RepositoryResponse.  # noqa: E501
        :type: str
        """

        self._remote_repository_owner = remote_repository_owner

    @property
    def remote_repository_name(self):
        """Gets the remote_repository_name of this RepositoryResponse.  # noqa: E501


        :return: The remote_repository_name of this RepositoryResponse.  # noqa: E501
        :rtype: str
        """
        return self._remote_repository_name

    @remote_repository_name.setter
    def remote_repository_name(self, remote_repository_name):
        """Sets the remote_repository_name of this RepositoryResponse.


        :param remote_repository_name: The remote_repository_name of this RepositoryResponse.  # noqa: E501
        :type: str
        """

        self._remote_repository_name = remote_repository_name

    @property
    def active_job(self):
        """Gets the active_job of this RepositoryResponse.  # noqa: E501

        The Tgstation.Server.Api.Models.Response.JobResponse started by the request, if any.  # noqa: E501

        :return: The active_job of this RepositoryResponse.  # noqa: E501
        :rtype: AllOfRepositoryResponseActiveJob
        """
        return self._active_job

    @active_job.setter
    def active_job(self, active_job):
        """Sets the active_job of this RepositoryResponse.

        The Tgstation.Server.Api.Models.Response.JobResponse started by the request, if any.  # noqa: E501

        :param active_job: The active_job of this RepositoryResponse.  # noqa: E501
        :type: AllOfRepositoryResponseActiveJob
        """

        self._active_job = active_job

    @property
    def reference(self):
        """Gets the reference of this RepositoryResponse.  # noqa: E501

        The branch or tag HEAD points to.  # noqa: E501

        :return: The reference of this RepositoryResponse.  # noqa: E501
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference):
        """Sets the reference of this RepositoryResponse.

        The branch or tag HEAD points to.  # noqa: E501

        :param reference: The reference of this RepositoryResponse.  # noqa: E501
        :type: str
        """

        self._reference = reference

    @property
    def committer_name(self):
        """Gets the committer_name of this RepositoryResponse.  # noqa: E501

        The name of the committer  # noqa: E501

        :return: The committer_name of this RepositoryResponse.  # noqa: E501
        :rtype: str
        """
        return self._committer_name

    @committer_name.setter
    def committer_name(self, committer_name):
        """Sets the committer_name of this RepositoryResponse.

        The name of the committer  # noqa: E501

        :param committer_name: The committer_name of this RepositoryResponse.  # noqa: E501
        :type: str
        """

        self._committer_name = committer_name

    @property
    def committer_email(self):
        """Gets the committer_email of this RepositoryResponse.  # noqa: E501

        The e-mail of the committer  # noqa: E501

        :return: The committer_email of this RepositoryResponse.  # noqa: E501
        :rtype: str
        """
        return self._committer_email

    @committer_email.setter
    def committer_email(self, committer_email):
        """Sets the committer_email of this RepositoryResponse.

        The e-mail of the committer  # noqa: E501

        :param committer_email: The committer_email of this RepositoryResponse.  # noqa: E501
        :type: str
        """

        self._committer_email = committer_email

    @property
    def access_user(self):
        """Gets the access_user of this RepositoryResponse.  # noqa: E501

        The username to access the git repository with  # noqa: E501

        :return: The access_user of this RepositoryResponse.  # noqa: E501
        :rtype: str
        """
        return self._access_user

    @access_user.setter
    def access_user(self, access_user):
        """Sets the access_user of this RepositoryResponse.

        The username to access the git repository with  # noqa: E501

        :param access_user: The access_user of this RepositoryResponse.  # noqa: E501
        :type: str
        """

        self._access_user = access_user

    @property
    def push_test_merge_commits(self):
        """Gets the push_test_merge_commits of this RepositoryResponse.  # noqa: E501

        If commits created from testmerges are pushed to the remote. Requires Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessUser and Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken to be set to function.  # noqa: E501

        :return: The push_test_merge_commits of this RepositoryResponse.  # noqa: E501
        :rtype: bool
        """
        return self._push_test_merge_commits

    @push_test_merge_commits.setter
    def push_test_merge_commits(self, push_test_merge_commits):
        """Sets the push_test_merge_commits of this RepositoryResponse.

        If commits created from testmerges are pushed to the remote. Requires Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessUser and Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken to be set to function.  # noqa: E501

        :param push_test_merge_commits: The push_test_merge_commits of this RepositoryResponse.  # noqa: E501
        :type: bool
        """

        self._push_test_merge_commits = push_test_merge_commits

    @property
    def create_git_hub_deployments(self):
        """Gets the create_git_hub_deployments of this RepositoryResponse.  # noqa: E501

        If GitHub deployments should be created. Requires Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessUser, Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken, and Tgstation.Server.Api.Models.Internal.RepositorySettings.PushTestMergeCommits to be set to function.  # noqa: E501

        :return: The create_git_hub_deployments of this RepositoryResponse.  # noqa: E501
        :rtype: bool
        """
        return self._create_git_hub_deployments

    @create_git_hub_deployments.setter
    def create_git_hub_deployments(self, create_git_hub_deployments):
        """Sets the create_git_hub_deployments of this RepositoryResponse.

        If GitHub deployments should be created. Requires Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessUser, Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken, and Tgstation.Server.Api.Models.Internal.RepositorySettings.PushTestMergeCommits to be set to function.  # noqa: E501

        :param create_git_hub_deployments: The create_git_hub_deployments of this RepositoryResponse.  # noqa: E501
        :type: bool
        """

        self._create_git_hub_deployments = create_git_hub_deployments

    @property
    def show_test_merge_committers(self):
        """Gets the show_test_merge_committers of this RepositoryResponse.  # noqa: E501

        If test merge commits are signed with the username of the person who merged it. Note this only affects future commits  # noqa: E501

        :return: The show_test_merge_committers of this RepositoryResponse.  # noqa: E501
        :rtype: bool
        """
        return self._show_test_merge_committers

    @show_test_merge_committers.setter
    def show_test_merge_committers(self, show_test_merge_committers):
        """Sets the show_test_merge_committers of this RepositoryResponse.

        If test merge commits are signed with the username of the person who merged it. Note this only affects future commits  # noqa: E501

        :param show_test_merge_committers: The show_test_merge_committers of this RepositoryResponse.  # noqa: E501
        :type: bool
        """

        self._show_test_merge_committers = show_test_merge_committers

    @property
    def auto_updates_keep_test_merges(self):
        """Gets the auto_updates_keep_test_merges of this RepositoryResponse.  # noqa: E501

        If test merge commits should be kept when auto updating. May cause merge conflicts which will block the update  # noqa: E501

        :return: The auto_updates_keep_test_merges of this RepositoryResponse.  # noqa: E501
        :rtype: bool
        """
        return self._auto_updates_keep_test_merges

    @auto_updates_keep_test_merges.setter
    def auto_updates_keep_test_merges(self, auto_updates_keep_test_merges):
        """Sets the auto_updates_keep_test_merges of this RepositoryResponse.

        If test merge commits should be kept when auto updating. May cause merge conflicts which will block the update  # noqa: E501

        :param auto_updates_keep_test_merges: The auto_updates_keep_test_merges of this RepositoryResponse.  # noqa: E501
        :type: bool
        """

        self._auto_updates_keep_test_merges = auto_updates_keep_test_merges

    @property
    def auto_updates_synchronize(self):
        """Gets the auto_updates_synchronize of this RepositoryResponse.  # noqa: E501

        If synchronization should occur when auto updating. Requries Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessUser and Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken to be set to function.  # noqa: E501

        :return: The auto_updates_synchronize of this RepositoryResponse.  # noqa: E501
        :rtype: bool
        """
        return self._auto_updates_synchronize

    @auto_updates_synchronize.setter
    def auto_updates_synchronize(self, auto_updates_synchronize):
        """Sets the auto_updates_synchronize of this RepositoryResponse.

        If synchronization should occur when auto updating. Requries Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessUser and Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken to be set to function.  # noqa: E501

        :param auto_updates_synchronize: The auto_updates_synchronize of this RepositoryResponse.  # noqa: E501
        :type: bool
        """

        self._auto_updates_synchronize = auto_updates_synchronize

    @property
    def post_test_merge_comment(self):
        """Gets the post_test_merge_comment of this RepositoryResponse.  # noqa: E501

        If test merging should create a comment. Requires Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken to be set to function.  # noqa: E501

        :return: The post_test_merge_comment of this RepositoryResponse.  # noqa: E501
        :rtype: bool
        """
        return self._post_test_merge_comment

    @post_test_merge_comment.setter
    def post_test_merge_comment(self, post_test_merge_comment):
        """Sets the post_test_merge_comment of this RepositoryResponse.

        If test merging should create a comment. Requires Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken to be set to function.  # noqa: E501

        :param post_test_merge_comment: The post_test_merge_comment of this RepositoryResponse.  # noqa: E501
        :type: bool
        """

        self._post_test_merge_comment = post_test_merge_comment

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RepositoryResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RepositoryResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
