# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SwarmServerResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'controller': 'bool',
        'address': 'str',
        'identifier': 'str'
    }

    attribute_map = {
        'controller': 'controller',
        'address': 'address',
        'identifier': 'identifier'
    }

    def __init__(self, controller=None, address=None, identifier=None):  # noqa: E501
        """SwarmServerResponse - a model defined in Swagger"""  # noqa: E501
        self._controller = None
        self._address = None
        self._identifier = None
        self.discriminator = None
        if controller is not None:
            self.controller = controller
        if address is not None:
            self.address = address
        if identifier is not None:
            self.identifier = identifier

    @property
    def controller(self):
        """Gets the controller of this SwarmServerResponse.  # noqa: E501

        If the Tgstation.Server.Api.Models.Response.SwarmServerResponse is the controller.  # noqa: E501

        :return: The controller of this SwarmServerResponse.  # noqa: E501
        :rtype: bool
        """
        return self._controller

    @controller.setter
    def controller(self, controller):
        """Sets the controller of this SwarmServerResponse.

        If the Tgstation.Server.Api.Models.Response.SwarmServerResponse is the controller.  # noqa: E501

        :param controller: The controller of this SwarmServerResponse.  # noqa: E501
        :type: bool
        """

        self._controller = controller

    @property
    def address(self):
        """Gets the address of this SwarmServerResponse.  # noqa: E501

        The public address of the server.  # noqa: E501

        :return: The address of this SwarmServerResponse.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this SwarmServerResponse.

        The public address of the server.  # noqa: E501

        :param address: The address of this SwarmServerResponse.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def identifier(self):
        """Gets the identifier of this SwarmServerResponse.  # noqa: E501

        The server's identifier.  # noqa: E501

        :return: The identifier of this SwarmServerResponse.  # noqa: E501
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this SwarmServerResponse.

        The server's identifier.  # noqa: E501

        :param identifier: The identifier of this SwarmServerResponse.  # noqa: E501
        :type: str
        """

        self._identifier = identifier

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SwarmServerResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SwarmServerResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
