# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'permission_set': 'AllOfUserGroupPermissionSet',
        'name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'permission_set': 'permissionSet',
        'name': 'name'
    }

    def __init__(self, id=None, permission_set=None, name=None):  # noqa: E501
        """UserGroup - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._permission_set = None
        self._name = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if permission_set is not None:
            self.permission_set = permission_set
        if name is not None:
            self.name = name

    @property
    def id(self):
        """Gets the id of this UserGroup.  # noqa: E501


        :return: The id of this UserGroup.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserGroup.


        :param id: The id of this UserGroup.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def permission_set(self):
        """Gets the permission_set of this UserGroup.  # noqa: E501

        The Tgstation.Server.Api.Models.PermissionSet of the Tgstation.Server.Api.Models.Internal.UserGroup.  # noqa: E501

        :return: The permission_set of this UserGroup.  # noqa: E501
        :rtype: AllOfUserGroupPermissionSet
        """
        return self._permission_set

    @permission_set.setter
    def permission_set(self, permission_set):
        """Sets the permission_set of this UserGroup.

        The Tgstation.Server.Api.Models.PermissionSet of the Tgstation.Server.Api.Models.Internal.UserGroup.  # noqa: E501

        :param permission_set: The permission_set of this UserGroup.  # noqa: E501
        :type: AllOfUserGroupPermissionSet
        """

        self._permission_set = permission_set

    @property
    def name(self):
        """Gets the name of this UserGroup.  # noqa: E501

        The name of the entity represented by the Tgstation.Server.Api.Models.NamedEntity.  # noqa: E501

        :return: The name of this UserGroup.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserGroup.

        The name of the entity represented by the Tgstation.Server.Api.Models.NamedEntity.  # noqa: E501

        :param name: The name of this UserGroup.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
