# coding: utf-8

"""
    TGS API

    A production scale tool for BYOND server management  # noqa: E501

    OpenAPI spec version: 9.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class InstancePermissionSetApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def instance_permission_set_controller_create(self, body, api, user_agent, instance, **kwargs):  # noqa: E501
        """Create an Tgstation.Server.Host.Models.InstancePermissionSet.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.instance_permission_set_controller_create(body, api, user_agent, instance, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Body44 body: The Tgstation.Server.Api.Models.Request.InstancePermissionSetRequest. (required)
        :param str api: The API version being used in the form \"Tgstation.Server.Api/[API version]\" (required)
        :param str user_agent: The user agent of the calling client. (required)
        :param int instance: The instance ID being accessed (required)
        :return: InstancePermissionSetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.instance_permission_set_controller_create_with_http_info(body, api, user_agent, instance, **kwargs)  # noqa: E501
        else:
            (data) = self.instance_permission_set_controller_create_with_http_info(body, api, user_agent, instance, **kwargs)  # noqa: E501
            return data

    def instance_permission_set_controller_create_with_http_info(self, body, api, user_agent, instance, **kwargs):  # noqa: E501
        """Create an Tgstation.Server.Host.Models.InstancePermissionSet.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.instance_permission_set_controller_create_with_http_info(body, api, user_agent, instance, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Body44 body: The Tgstation.Server.Api.Models.Request.InstancePermissionSetRequest. (required)
        :param str api: The API version being used in the form \"Tgstation.Server.Api/[API version]\" (required)
        :param str user_agent: The user agent of the calling client. (required)
        :param int instance: The instance ID being accessed (required)
        :return: InstancePermissionSetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'api', 'user_agent', 'instance']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method instance_permission_set_controller_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `instance_permission_set_controller_create`")  # noqa: E501
        # verify the required parameter 'api' is set
        if ('api' not in params or
                params['api'] is None):
            raise ValueError("Missing the required parameter `api` when calling `instance_permission_set_controller_create`")  # noqa: E501
        # verify the required parameter 'user_agent' is set
        if ('user_agent' not in params or
                params['user_agent'] is None):
            raise ValueError("Missing the required parameter `user_agent` when calling `instance_permission_set_controller_create`")  # noqa: E501
        # verify the required parameter 'instance' is set
        if ('instance' not in params or
                params['instance'] is None):
            raise ValueError("Missing the required parameter `instance` when calling `instance_permission_set_controller_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'api' in params:
            header_params['Api'] = params['api']  # noqa: E501
        if 'user_agent' in params:
            header_params['User-Agent'] = params['user_agent']  # noqa: E501
        if 'instance' in params:
            header_params['Instance'] = params['instance']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Token_Authorization_Scheme']  # noqa: E501

        return self.api_client.call_api(
            '/InstancePermissionSet', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InstancePermissionSetResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def instance_permission_set_controller_delete(self, api, user_agent, instance, id, **kwargs):  # noqa: E501
        """Delete an Tgstation.Server.Host.Models.InstancePermissionSet.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.instance_permission_set_controller_delete(api, user_agent, instance, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str api: The API version being used in the form \"Tgstation.Server.Api/[API version]\" (required)
        :param str user_agent: The user agent of the calling client. (required)
        :param int instance: The instance ID being accessed (required)
        :param int id: The Tgstation.Server.Api.Models.Internal.InstancePermissionSet.PermissionSetId to delete. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.instance_permission_set_controller_delete_with_http_info(api, user_agent, instance, id, **kwargs)  # noqa: E501
        else:
            (data) = self.instance_permission_set_controller_delete_with_http_info(api, user_agent, instance, id, **kwargs)  # noqa: E501
            return data

    def instance_permission_set_controller_delete_with_http_info(self, api, user_agent, instance, id, **kwargs):  # noqa: E501
        """Delete an Tgstation.Server.Host.Models.InstancePermissionSet.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.instance_permission_set_controller_delete_with_http_info(api, user_agent, instance, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str api: The API version being used in the form \"Tgstation.Server.Api/[API version]\" (required)
        :param str user_agent: The user agent of the calling client. (required)
        :param int instance: The instance ID being accessed (required)
        :param int id: The Tgstation.Server.Api.Models.Internal.InstancePermissionSet.PermissionSetId to delete. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['api', 'user_agent', 'instance', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method instance_permission_set_controller_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'api' is set
        if ('api' not in params or
                params['api'] is None):
            raise ValueError("Missing the required parameter `api` when calling `instance_permission_set_controller_delete`")  # noqa: E501
        # verify the required parameter 'user_agent' is set
        if ('user_agent' not in params or
                params['user_agent'] is None):
            raise ValueError("Missing the required parameter `user_agent` when calling `instance_permission_set_controller_delete`")  # noqa: E501
        # verify the required parameter 'instance' is set
        if ('instance' not in params or
                params['instance'] is None):
            raise ValueError("Missing the required parameter `instance` when calling `instance_permission_set_controller_delete`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `instance_permission_set_controller_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'api' in params:
            header_params['Api'] = params['api']  # noqa: E501
        if 'user_agent' in params:
            header_params['User-Agent'] = params['user_agent']  # noqa: E501
        if 'instance' in params:
            header_params['Instance'] = params['instance']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Token_Authorization_Scheme']  # noqa: E501

        return self.api_client.call_api(
            '/InstancePermissionSet/{id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def instance_permission_set_controller_get_id(self, api, user_agent, instance, id, **kwargs):  # noqa: E501
        """Gets a specific Tgstation.Server.Api.Models.Internal.InstancePermissionSet.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.instance_permission_set_controller_get_id(api, user_agent, instance, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str api: The API version being used in the form \"Tgstation.Server.Api/[API version]\" (required)
        :param str user_agent: The user agent of the calling client. (required)
        :param int instance: The instance ID being accessed (required)
        :param int id: The Tgstation.Server.Api.Models.Internal.InstancePermissionSet.PermissionSetId. (required)
        :return: InstancePermissionSetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.instance_permission_set_controller_get_id_with_http_info(api, user_agent, instance, id, **kwargs)  # noqa: E501
        else:
            (data) = self.instance_permission_set_controller_get_id_with_http_info(api, user_agent, instance, id, **kwargs)  # noqa: E501
            return data

    def instance_permission_set_controller_get_id_with_http_info(self, api, user_agent, instance, id, **kwargs):  # noqa: E501
        """Gets a specific Tgstation.Server.Api.Models.Internal.InstancePermissionSet.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.instance_permission_set_controller_get_id_with_http_info(api, user_agent, instance, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str api: The API version being used in the form \"Tgstation.Server.Api/[API version]\" (required)
        :param str user_agent: The user agent of the calling client. (required)
        :param int instance: The instance ID being accessed (required)
        :param int id: The Tgstation.Server.Api.Models.Internal.InstancePermissionSet.PermissionSetId. (required)
        :return: InstancePermissionSetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['api', 'user_agent', 'instance', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method instance_permission_set_controller_get_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'api' is set
        if ('api' not in params or
                params['api'] is None):
            raise ValueError("Missing the required parameter `api` when calling `instance_permission_set_controller_get_id`")  # noqa: E501
        # verify the required parameter 'user_agent' is set
        if ('user_agent' not in params or
                params['user_agent'] is None):
            raise ValueError("Missing the required parameter `user_agent` when calling `instance_permission_set_controller_get_id`")  # noqa: E501
        # verify the required parameter 'instance' is set
        if ('instance' not in params or
                params['instance'] is None):
            raise ValueError("Missing the required parameter `instance` when calling `instance_permission_set_controller_get_id`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `instance_permission_set_controller_get_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'api' in params:
            header_params['Api'] = params['api']  # noqa: E501
        if 'user_agent' in params:
            header_params['User-Agent'] = params['user_agent']  # noqa: E501
        if 'instance' in params:
            header_params['Instance'] = params['instance']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Token_Authorization_Scheme']  # noqa: E501

        return self.api_client.call_api(
            '/InstancePermissionSet/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InstancePermissionSetResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def instance_permission_set_controller_list(self, api, user_agent, instance, **kwargs):  # noqa: E501
        """Lists Tgstation.Server.Host.Models.InstancePermissionSets for the instance.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.instance_permission_set_controller_list(api, user_agent, instance, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str api: The API version being used in the form \"Tgstation.Server.Api/[API version]\" (required)
        :param str user_agent: The user agent of the calling client. (required)
        :param int instance: The instance ID being accessed (required)
        :param int page: The current page.
        :param int page_size: The page size.
        :return: PaginatedInstancePermissionSetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.instance_permission_set_controller_list_with_http_info(api, user_agent, instance, **kwargs)  # noqa: E501
        else:
            (data) = self.instance_permission_set_controller_list_with_http_info(api, user_agent, instance, **kwargs)  # noqa: E501
            return data

    def instance_permission_set_controller_list_with_http_info(self, api, user_agent, instance, **kwargs):  # noqa: E501
        """Lists Tgstation.Server.Host.Models.InstancePermissionSets for the instance.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.instance_permission_set_controller_list_with_http_info(api, user_agent, instance, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str api: The API version being used in the form \"Tgstation.Server.Api/[API version]\" (required)
        :param str user_agent: The user agent of the calling client. (required)
        :param int instance: The instance ID being accessed (required)
        :param int page: The current page.
        :param int page_size: The page size.
        :return: PaginatedInstancePermissionSetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['api', 'user_agent', 'instance', 'page', 'page_size']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method instance_permission_set_controller_list" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'api' is set
        if ('api' not in params or
                params['api'] is None):
            raise ValueError("Missing the required parameter `api` when calling `instance_permission_set_controller_list`")  # noqa: E501
        # verify the required parameter 'user_agent' is set
        if ('user_agent' not in params or
                params['user_agent'] is None):
            raise ValueError("Missing the required parameter `user_agent` when calling `instance_permission_set_controller_list`")  # noqa: E501
        # verify the required parameter 'instance' is set
        if ('instance' not in params or
                params['instance'] is None):
            raise ValueError("Missing the required parameter `instance` when calling `instance_permission_set_controller_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501

        header_params = {}
        if 'api' in params:
            header_params['Api'] = params['api']  # noqa: E501
        if 'user_agent' in params:
            header_params['User-Agent'] = params['user_agent']  # noqa: E501
        if 'instance' in params:
            header_params['Instance'] = params['instance']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Token_Authorization_Scheme']  # noqa: E501

        return self.api_client.call_api(
            '/InstancePermissionSet/List', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaginatedInstancePermissionSetResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def instance_permission_set_controller_read(self, api, user_agent, instance, **kwargs):  # noqa: E501
        """Read the active Tgstation.Server.Host.Models.InstancePermissionSet.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.instance_permission_set_controller_read(api, user_agent, instance, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str api: The API version being used in the form \"Tgstation.Server.Api/[API version]\" (required)
        :param str user_agent: The user agent of the calling client. (required)
        :param int instance: The instance ID being accessed (required)
        :return: InstancePermissionSetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.instance_permission_set_controller_read_with_http_info(api, user_agent, instance, **kwargs)  # noqa: E501
        else:
            (data) = self.instance_permission_set_controller_read_with_http_info(api, user_agent, instance, **kwargs)  # noqa: E501
            return data

    def instance_permission_set_controller_read_with_http_info(self, api, user_agent, instance, **kwargs):  # noqa: E501
        """Read the active Tgstation.Server.Host.Models.InstancePermissionSet.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.instance_permission_set_controller_read_with_http_info(api, user_agent, instance, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str api: The API version being used in the form \"Tgstation.Server.Api/[API version]\" (required)
        :param str user_agent: The user agent of the calling client. (required)
        :param int instance: The instance ID being accessed (required)
        :return: InstancePermissionSetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['api', 'user_agent', 'instance']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method instance_permission_set_controller_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'api' is set
        if ('api' not in params or
                params['api'] is None):
            raise ValueError("Missing the required parameter `api` when calling `instance_permission_set_controller_read`")  # noqa: E501
        # verify the required parameter 'user_agent' is set
        if ('user_agent' not in params or
                params['user_agent'] is None):
            raise ValueError("Missing the required parameter `user_agent` when calling `instance_permission_set_controller_read`")  # noqa: E501
        # verify the required parameter 'instance' is set
        if ('instance' not in params or
                params['instance'] is None):
            raise ValueError("Missing the required parameter `instance` when calling `instance_permission_set_controller_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'api' in params:
            header_params['Api'] = params['api']  # noqa: E501
        if 'user_agent' in params:
            header_params['User-Agent'] = params['user_agent']  # noqa: E501
        if 'instance' in params:
            header_params['Instance'] = params['instance']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Token_Authorization_Scheme']  # noqa: E501

        return self.api_client.call_api(
            '/InstancePermissionSet', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InstancePermissionSetResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def instance_permission_set_controller_update(self, body, api, user_agent, instance, **kwargs):  # noqa: E501
        """Update the permissions for an Tgstation.Server.Host.Models.InstancePermissionSet.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.instance_permission_set_controller_update(body, api, user_agent, instance, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Body48 body: The Tgstation.Server.Api.Models.Request.InstancePermissionSetRequest. (required)
        :param str api: The API version being used in the form \"Tgstation.Server.Api/[API version]\" (required)
        :param str user_agent: The user agent of the calling client. (required)
        :param int instance: The instance ID being accessed (required)
        :return: InstancePermissionSetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.instance_permission_set_controller_update_with_http_info(body, api, user_agent, instance, **kwargs)  # noqa: E501
        else:
            (data) = self.instance_permission_set_controller_update_with_http_info(body, api, user_agent, instance, **kwargs)  # noqa: E501
            return data

    def instance_permission_set_controller_update_with_http_info(self, body, api, user_agent, instance, **kwargs):  # noqa: E501
        """Update the permissions for an Tgstation.Server.Host.Models.InstancePermissionSet.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.instance_permission_set_controller_update_with_http_info(body, api, user_agent, instance, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Body48 body: The Tgstation.Server.Api.Models.Request.InstancePermissionSetRequest. (required)
        :param str api: The API version being used in the form \"Tgstation.Server.Api/[API version]\" (required)
        :param str user_agent: The user agent of the calling client. (required)
        :param int instance: The instance ID being accessed (required)
        :return: InstancePermissionSetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'api', 'user_agent', 'instance']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method instance_permission_set_controller_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `instance_permission_set_controller_update`")  # noqa: E501
        # verify the required parameter 'api' is set
        if ('api' not in params or
                params['api'] is None):
            raise ValueError("Missing the required parameter `api` when calling `instance_permission_set_controller_update`")  # noqa: E501
        # verify the required parameter 'user_agent' is set
        if ('user_agent' not in params or
                params['user_agent'] is None):
            raise ValueError("Missing the required parameter `user_agent` when calling `instance_permission_set_controller_update`")  # noqa: E501
        # verify the required parameter 'instance' is set
        if ('instance' not in params or
                params['instance'] is None):
            raise ValueError("Missing the required parameter `instance` when calling `instance_permission_set_controller_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'api' in params:
            header_params['Api'] = params['api']  # noqa: E501
        if 'user_agent' in params:
            header_params['User-Agent'] = params['user_agent']  # noqa: E501
        if 'instance' in params:
            header_params['Instance'] = params['instance']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Token_Authorization_Scheme']  # noqa: E501

        return self.api_client.call_api(
            '/InstancePermissionSet', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InstancePermissionSetResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
